gaurav_gc/README.md
=> Created + updated Gaurav's README

brett_buskirk/README.md
@gaurav-gc, I have added to my README file.
=> Updated brett's README

chris_linton/README.md
=> made change to README.md

jason_rolle/README.md
=> Modify readme

diana_delos_reyes/README.md
=> added test text to ReadME

brendan_ngwa_nforbi/README.md
Hey, completing this challenge... updating the README
=> Updated RADME

jason_rolle/first_python_challenge.py
=> uploading first python challenge

maleka_brown/first_python_challenge.py
=> uploading first python challenge.

brendan_ngwa_nforbi/first_python_challenge.py
Hi Gaurav, just finished my first python challenge... hopefully this suffices
=> Updated first python challenge file

brett_buskirk/first_python_challenge.py
@gaurav-gc, here is my completed python challenge!
=> Completed first python challenge

jason_rolle/primitive_data_challenges/Tempature.py
=> complete temperature challeng

brett_buskirk/temperature.py
Here's the completed first challenge!
=> Finished the temperature.py challenge

chris_linton/nba_challenge.py, chris_linton/temperature.py
=> Temperature challenge

brett_buskirk/snippets_challenge.py, brett_buskirk/stocks_challenge.py
Here are the completed snippets and stocks challenges. Man did I miss our room tonight! 😄
=> Completed snippets and stocks challenges

lee_harvey/class_scripts/nba_challenge.py, lee_harvey/class_scripts/snippets_challenge.py, lee_harvey/class_scripts/stocks_challenge.py, lee_harvey/class_scripts/temperature.py
A little advanced for this challenge, but I hope it satisfies the challenge. 
Modified so that your recommendations are reflected.
Changed the function that was incorrect.
Added the snippets and stock challenges.
=> Would you merge my request once you review, Lee?

brendan_ngwa_nforbi/nba_challenge.py, brendan_ngwa_nforbi/temperature.py
Made changes to the temp challenge
=> Updated temperature challenge

chris_linton/box_office_challenge.py
hi gaurav, hope I'm doing these pushes and pull requests correctly
=> Box Office Challenge

brett_buskirk/box_office_challenge.py
Here is the finished box office challenge! Love to keep the momentum rolling.
=> Completed the box office challenge

brendan_ngwa_nforbi/box_office_challenge.py, brendan_ngwa_nforbi/restaurants_challenge.py, snippets_challenge.py, stocks_challenge.py
Updated the following files: snippets_challenge.py, stocks_challenge.py, box_office_challenge.py, restaurants_challenge.py.
=> Updated four files

brett_buskirk/restaurants_challenge.py
Here's my assignment from yesterday! Looks like we got to do some pair programming. Bummer I missed that...
=> Completed Restaurants Challenge

chris_linton/restaurants_challenge.py
=> Restaurants Challenge

lee_harvey/class_scripts/restaurant_challenge.py
=> adding restaurant_challenge.py

brett_buskirk/spotify_challenge.md
Here is the Spotify Challenge in a markdown file.
=> Finished spotify challenge
